### ISSUE TITLE
Resolve hostile fork

### ISSUE THREAD

**Issue by quozl** [sugarlabs/geotonky-activity#3]
https://github.com/lesivan/GeoTonky is the upstream repository for this repository, yet this repository is not a fork of that repository, this repository has much older files, and this repository has files from a bundle that was added to the ASLO moderation queue but was never released because we lost all our active moderators.

A new fork has been created; https://github.com/sugarlabs/GeoTonky

* [x] complete all other issues and open pull requests in https://github.com/sugarlabs/geotonky-activity,
* [x] work to make both repositories contain the same files,
* [ ] delete https://github.com/sugarlabs/geotonky-activity
* [ ] rename https://github.com/sugarlabs/GeoTonky as https://github.com/sugarlabs/geotonky-activity

**Comment by yashagrawal3** [comment]
Checked that both repositories contain the same files using meld, we can go forward deleting this activity.
